### ISSUE TITLE
TestDNSResolution: Seg fault in udp_sendto

### ISSUE THREAD

**Issue by jaylogue** [openweave/openweave-core#124]
The TestDNSResolution unit test fails with a segmentation fault in udp_sendto() when built for LwIP.

```
#0  0x000000000047abee in udp_sendto (pcb=0x900, p=0x6dcac8 <ram_heap+8>, dst_ip=0x6dc260 <dns_servers>, dst_port=53)
    at /home/jay/projects/openweave-core/src/lwip/../../third_party/lwip/repo/lwip/src/core/udp.c:532
#1  0x000000000045f89d in dns_send (idx=1 '\001') at /home/jay/projects/openweave-core/src/lwip/../../third_party/lwip/repo/lwip/src/core/dns.c:886
#2  0x000000000046034e in dns_check_entry (i=1 '\001') at /home/jay/projects/openweave-core/src/lwip/../../third_party/lwip/repo/lwip/src/core/dns.c:1150
#3  0x0000000000460434 in dns_check_entries () at /home/jay/projects/openweave-core/src/lwip/../../third_party/lwip/repo/lwip/src/core/dns.c:1184
#4  0x000000000045eb4b in dns_tmr () at /home/jay/projects/openweave-core/src/lwip/../../third_party/lwip/repo/lwip/src/core/dns.c:424
#5  0x0000000000482b67 in cyclic_timer (arg=0x6c5da0 <lwip_cyclic_timers+96>)
    at /home/jay/projects/openweave-core/src/lwip/../../third_party/lwip/repo/lwip/src/core/timeouts.c:177
#6  0x0000000000482f9b in sys_check_timeouts () at /home/jay/projects/openweave-core/src/lwip/../../third_party/lwip/repo/lwip/src/core/timeouts.c:364
#7  0x000000000048307f in sys_timeouts_mbox_fetch (mbox=0x6dbbd0 <mbox>, msg=0x7ffff69dcec0)
    at /home/jay/projects/openweave-core/src/lwip/../../third_party/lwip/repo/lwip/src/core/timeouts.c:437
#8  0x000000000045df95 in tcpip_thread (arg=0x0) at /home/jay/projects/openweave-core/src/lwip/../../third_party/lwip/repo/lwip/src/api/tcpip.c:107
#9  0x00007ffff7bc4184 in start_thread (arg=0x7ffff69dd700) at pthread_create.c:312
#10 0x00007ffff71fe03d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

The root cause of the problem is unclear, but seems to be stem from a logic bug in dns_recv() which fails to reset the state of a dns_table_entry when no answer is received after trying all available DNS servers.

**Comment by jaylogue** [comment]
Fixed in PR #124 / commit d8f4273b1a.
