### ISSUE TITLE
Inet Layer Causes a Segment Fault When Running Inet Layer TCP End Point Test against LwIP

### ISSUE THREAD

**Issue by gerickson** [openweave/openweave-core#143]
There appears to be a segment fault in both the sender and receiver in the TCP portion of the Inet layer when running the Inet layer functional test built against LwIP when the sender attempts to, and fails, to connect to the receiver.

**Comment by gerickson** [comment]
The receiver segment faults here:

```
Thread 2 "TestInetLayer" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6e85700 (LWP 7347)]
0x0000555555709217 in tcp_input (
    p=0x555555a018e0 <memp_memory_PBUF_POOL_base+14112>, 
    inp=0x5555559e1340 <netIF>)
    at third_party/lwip/repo/lwip/src/core/tcp_in.c:292
292	      if ((pcb->netif_idx != NETIF_NO_INDEX) &&
(gdb) where
#0  0x0000555555709217 in tcp_input (
    p=0x555555a018e0 <memp_memory_PBUF_POOL_base+14112>, 
    inp=0x5555559e1340 <netIF>)
    at third_party/lwip/repo/lwip/src/core/tcp_in.c:292
#1  0x000055555571af2a in ip6_input (
    p=0x555555a018e0 <memp_memory_PBUF_POOL_base+14112>, 
    inp=0x5555559e1340 <netIF>)
    at third_party/lwip/repo/lwip/src/core/ipv6/ip6.c:811
#2  0x000055555571176d in ethernet_input (
    p=0x555555a018e0 <memp_memory_PBUF_POOL_base+14112>, 
    netif=0x5555559e1340 <netIF>)
    at third_party/lwip/repo/lwip/src/netif/ethernet.c:223
#3  0x00005555556f6f22 in tcpip_thread (arg=0x0)
    at third_party/lwip/repo/lwip/src/api/tcpip.c:130
#4  0x00007ffff7bbd6db in start_thread (arg=0x7ffff6e85700)
    at pthread_create.c:463
#5  0x00007ffff755d88f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by gerickson** [comment]
This issue has been fixed upstream at http://git.savannah.nongnu.org/cgit/lwip.git/commit/?id=0545eba002d25a0116daf7dddda8e7a7ce5527cf.

Applying the patch, the sender and receiver no longer segment fault.

**Comment by gerickson** [comment]
https://github.com/openweave/openweave-core/pull/150
