### ISSUE TITLE
test_inet_01 test case is failing on my setup

### ISSUE THREAD

**Issue by jenniexie** [openweave/openweave-core#164]
[test_inet_01.py.log](https://github.com/openweave/openweave-core/files/2906700/test_inet_01.py.log)

**Comment by jenniexie** [comment]
2019-02-26 09:13:28,873 [WeaveInet] [localhost] WeaveInet: Could not find IP address of the receiver node, 01-WifiNode-Rx
E
======================================================================
ERROR: test_weave_inet (__main__.test_weave_inet_01)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/google/home/jexie/github/openweave-core/src/test-apps/happy/tests/standalone/inet/test_inet_01.py", line 158, in test_weave_inet
    value, data = self.__run_inet_test_between(self.sender, self.receiver, interface, network, transport, prefix, tx_size, rx_tx_length)
  File "/usr/local/google/home/jexie/github/openweave-core/src/test-apps/happy/tests/standalone/inet/test_inet_01.py", line 195, in __run_inet_test_between
    ret = weave_inet.run()
  File "/usr/local/google/home/jexie/github/openweave-core/src/test-apps/happy/test-templates/WeaveInet.py", line 371, in run
    self.__pre_check()
  File "/usr/local/google/home/jexie/github/openweave-core/src/test-apps/happy/test-templates/WeaveInet.py", line 173, in __pre_check
    self.__log_error_and_exit(emsg)
  File "/usr/local/google/home/jexie/github/openweave-core/src/test-apps/happy/test-templates/WeaveInet.py", line 102, in __log_error_and_exit
    sys.exit(1)
SystemExit: 1

----------------------------------------------------------------------
Ran 1 test in 27.435s
